<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2011 sp1 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:clitype="clitype" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:iso4217="http://www.xbrl.org/2003/iso4217" xmlns:ix="http://www.xbrl.org/2008/inlineXBRL" xmlns:java="java" xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:xbrldi="http://xbrl.org/2006/xbrldi" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:altova="http://www.altova.com" exclude-result-prefixes="clitype fn iso4217 ix java link xbrldi xbrli xlink xs xsi altova">
	<xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.01 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:variable name="altova:nPxPerIn" select="96"/>
	<xsl:template match="/">
		<html>
			<head>
				<title>
					<xsl:text> </xsl:text>
				</title>
				<meta http-equiv="X-UA-Compatible" content="IE=7"/>
				<xsl:comment>[if IE]&gt;&lt;STYLE type=&quot;text/css&quot;&gt;.altova-rotate-left-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3)} .altova-rotate-right-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=1)} &lt;/STYLE&gt;&lt;![endif]</xsl:comment>
				<xsl:comment>[if !IE]&gt;&lt;!</xsl:comment>
				<style type="text/css">.altova-rotate-left-textbox{-webkit-transform: rotate(-90deg) translate(-100%, 0%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(-90deg) translate(-100%, 0%); -moz-transform-origin: 0% 0%}.altova-rotate-right-textbox{-webkit-transform: rotate(90deg) translate(0%, -100%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(90deg) translate(0%, -100%); -moz-transform-origin: 0% 0%}</style>
				<xsl:comment>&lt;![endif]</xsl:comment>
				<style type="text/css">@page { margin-left:0.5in; margin-right:0.5in; margin-top:0.5in; margin-bottom:0.5in } @media print { br.altova-page-break { page-break-before: always; } }</style>
			</head>
			<body>
				
				<table align="center" style="background-color:white; font:12; font-family:Times New Roman; height:auto; table-omit-footer-at-break:true; vertical-align:middle; " border="1" cellpadding="0" cellspacing="0" height="100%" width="auto">
					<xsl:variable name="altova:CurrContextGrid_0FCA5CD0" select="."/>
					<thead style="background-color:silver; color:black; font:12px; font-family:Times New Roman; font-weight:bold; ">
						<tr style="background-color:#dce9f2; height:0.01in; overflow:auto; text-align:center; ">
							<th style="font-size:12px; text-align:center; vertical-align:middle; width:3in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>EMERTIMI I STRUKTURES</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>OF0</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>OF1</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; width:0,1in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>OF2</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; width:0,1in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>OF3</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; width:0,1in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>OF4</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; width:0,1in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>OF5</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; width:0,1in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>OF6</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; width:0,1in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>OF7</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; width:0,1in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>OF8</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; width:0.40in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>Shuma</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; width:0,2in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>OR5</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; width:0,2in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>OR6</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; width:0,2in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>OR7</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; width:0,2in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>OR8</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; width:0,2in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>OR9</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; width:0.40in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>Shuma</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; width:0,2in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>OR1</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; width:0,2in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>OR3</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; width:0.40in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>Shuma</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; width:0.2in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>C1</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; width:0.2in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>C2</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; width:0.2in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>C3</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; width:0.2in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>C4</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; width:0.2in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>C5</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; width:0.40in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>Shuma</xsl:text>
								</span>
							</th>
							<th style="font-size:12px; text-align:center; width:0.38in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; ">
									<xsl:text>Totali </xsl:text>
								</span>
							</th>
						</tr>
						
					</thead>
					
					<tbody style="vertical-align:middle; ">
					<tr style="height:0.01in;background-color:#ECC5A8; ">
							<td style=" font-size:12px; text-align:center; vertical-align:middle; width:3in; ">
								<span style="font:10px; font-family:Times New Roman; font-size:12px; font-weight:bold; table-omit-footer-at-break:true; ">
									<xsl:text>TOTAL FA</xsl:text>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="sum(//dataArray/OF0) div 2"/>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="sum(//dataArray/OF1) div 2"/>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; width:0,1in; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="sum(//dataArray/OF2) div 2"/>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; width:0,1in; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="sum(//dataArray/OF3) div 2"/>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; width:0,1in; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="sum(//dataArray/OF4) div 2"/>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; width:0,1in; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="sum(//dataArray/OF5) div 2"/>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; width:0,1in; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="sum(//dataArray/OF6) div 2"/>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; width:0,1in; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="sum(//dataArray/OF7) div 2"/>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; width:0,1in; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="sum(//dataArray/OF8) div 2"/>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; width:0.40in; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="(sum(//dataArray/OF0)+sum(//dataArray/OF1)+sum(//dataArray/OF2)+sum(//dataArray/OF3)+sum(//dataArray/OF4)+sum(//dataArray/OF5)+sum(//dataArray/OF6)+sum(//dataArray/OF7)+sum(//dataArray/OF8) )div 2"/>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; width:0,2in; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="sum(//dataArray/OR5) div 2"/>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; width:0,2in; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="sum(//dataArray/OR6) div 2"/>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; width:0,2in; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="sum(//dataArray/OR7) div 2"/>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; width:0,2in; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="sum(//dataArray/OR8) div 2"/>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; width:0,2in; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="sum(//dataArray/OR9) div 2"/>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; width:0.40in; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="(sum(//dataArray/OR5)+sum(//dataArray/OR6)+sum(//dataArray/OR7)+sum(//dataArray/OR8)+sum(//dataArray/OR9)) div 2"/>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; width:0,2in; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="sum(//dataArray/OR1) div 2"/>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; width:0,2in; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="sum(//dataArray/OR3) div 2"/>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; width:0.40in; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="(sum(//dataArray/OR1)+sum(//dataArray/OR3)) div 2"/>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; width:0.2in; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="sum(//dataArray/C1) div 2"/>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; width:0.2in; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="sum(//dataArray/C2) div 2"/>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; width:0.2in; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="sum(//dataArray/C3) div 2"/>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; width:0.2in; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="sum(//dataArray/C4) div 2"/>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; width:0.2in; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="sum(//dataArray/C5) div 2"/>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; width:0.40in; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="(sum(//dataArray/C1)+sum(//dataArray/C2)+sum(//dataArray/C3)+sum(//dataArray/C4)+sum(//dataArray/C5)) div 2"/>
								</span>
							</td>
							<td style=" font-size:12px; text-align:center; width:0.38in; ">
								<span style="font-family:Times New Roman; font-weight:bold; vertical-align:middle; ">
									<xsl:value-of select="(sum(//dataArray/OF0)+sum(//dataArray/OF1)+sum(//dataArray/OF2)+sum(//dataArray/OF3)+sum(//dataArray/OF4)+sum(//dataArray/OF5)+sum(//dataArray/OF6)+sum(//dataArray/OF7)+sum(//dataArray/OF8)+sum(//dataArray/OR5)+sum(//dataArray/OR6)+sum(//dataArray/OR7)+sum(//dataArray/OR8)+sum(//dataArray/OR9)+sum(//dataArray/OR1)+sum(//dataArray/OR3)+sum(//dataArray/C1)+sum(//dataArray/C2)+sum(//dataArray/C3)+sum(//dataArray/C4)+sum(//dataArray/C5)) div 2"/>
								</span>
							</td>
						</tr>
						<xsl:for-each select="$XML">
							<xsl:for-each select="dataArray">
								<xsl:for-each select="dataArray">
								<xsl:if test="type='force'">
									<tr style="height:0.01in;background-color:#D3D1D2; text-align:right; vertical-align:middle;font-weight:bold; ">
										<td style="font-size:12px; text-align:center; vertical-align:middle; width:3in; ">
											<xsl:for-each select="unit">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; ">
											<xsl:for-each select="OF0">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; ">
											<xsl:for-each select="OF1">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font:12; font-family:Times New Roman; font-size:12px; text-align:center; width:0,1in; ">
											<xsl:for-each select="OF2">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0,1in; ">
											<xsl:for-each select="OF3">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0,1in; ">
											<xsl:for-each select="OF4">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0,1in; ">
											<xsl:for-each select="OF5">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0,1in; ">
											<xsl:for-each select="OF6">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0,1in; ">
											<xsl:for-each select="OF7">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0,1in; ">
											<xsl:for-each select="OF8">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style=" background-color:#ECC5A8; font-size:12px; text-align:center; width:0.40in; ">
											<span style="font:12px; font-family:Times New Roman; font-size:12px; font-weight:bold; vertical-align:middle; ">
												<xsl:value-of select="OF0+OF1+OF2+OF3+OF4+OF5+OF6+OF7+OF8"/>
											</span>
										</td>
										<td style="font-size:12px; text-align:center; width:0,2in; ">
											<xsl:for-each select="OR5">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0,2in; ">
											<xsl:for-each select="OR6">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0,2in; ">
											<xsl:for-each select="OR7">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0,2in; ">
											<xsl:for-each select="OR8">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0,2in; ">
											<xsl:for-each select="OR9">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style=" font-size:12px; background-color:#ECC5A8; text-align:center; width:0.40in; ">
											<span style="font:12px; font-family:Times New Roman; font-size:12px; font-weight:bold; vertical-align:middle; ">
												<xsl:value-of select="OR5+OR6+OR7+OR8+OR9"/>
											</span>
										</td>
										<td style="font-size:12px; text-align:center; width:0,2in; ">
											<xsl:for-each select="OR1">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0,2in; ">
											<xsl:for-each select="OR3">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style=" font-size:12px; background-color:#ECC5A8; text-align:center; width:0.40in; ">
											<span style="font:12px; font-family:Times New Roman; font-size:12px; font-weight:bold; vertical-align:middle; ">
												<xsl:value-of select="OR1+OR3"/>
											</span>
										</td>
										<td style="font-size:12px; text-align:center; width:0.2in; ">
											<xsl:for-each select="C1">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0.2in; ">
											<xsl:for-each select="C2">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0.2in; ">
											<xsl:for-each select="C3">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0.2in; ">
											<xsl:for-each select="C4">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0.2in; ">
											<xsl:for-each select="C5">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style=" font-size:12px; background-color:#ECC5A8; text-align:center; width:0.40in; ">
											<span style="font:12px; font-family:Times New Roman; font-size:12px; font-weight:bold; vertical-align:middle; ">
												<xsl:value-of select="C1+C2+C3+C4+C5"/>
											</span>
										</td>
										<td style="background-color:#ECC5A8; font-size:12px; text-align:center; width:0.38in; ">
											<span style="font:12px; font-family:Times New Roman; font-size:12px; font-weight:bold; vertical-align:middle; ">
												<xsl:value-of select="OF0+OF1+OF2+OF3+OF4+OF5+OF6+OF7+OF8+OR5+OR6+OR7+OR8+OR9+OR1+OR3+C1+C2+C3+C4+C5"/>
											</span>
										</td>
									</tr>
									</xsl:if>
									<xsl:if test="type='unit'">
									<tr style="height:0.01in;  vertical-align:middle; ">
										<td style="font-size:12px; text-align:right; vertical-align:middle; width:3in; ">
											<xsl:for-each select="unit">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; ">
											<xsl:for-each select="OF0">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; ">
											<xsl:for-each select="OF1">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font:12; font-family:Times New Roman; font-size:12px; text-align:center; width:0,1in; ">
											<xsl:for-each select="OF2">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0,1in; ">
											<xsl:for-each select="OF3">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0,1in; ">
											<xsl:for-each select="OF4">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0,1in; ">
											<xsl:for-each select="OF5">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0,1in; ">
											<xsl:for-each select="OF6">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0,1in; ">
											<xsl:for-each select="OF7">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0,1in; ">
											<xsl:for-each select="OF8">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style=" background-color:#ECC5A8; font-size:12px;text-align:center; width:0.40in; ">
											<span style="font:12px; font-family:Times New Roman; font-size:12px; font-weight:bold; vertical-align:middle; ">
												<xsl:value-of select="OF0+OF1+OF2+OF3+OF4+OF5+OF6+OF7+OF8"/>
											</span>
										</td>
										<td style="font-size:12px; text-align:center; width:0,2in; ">
											<xsl:for-each select="OR5">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0,2in; ">
											<xsl:for-each select="OR6">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0,2in; ">
											<xsl:for-each select="OR7">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0,2in; ">
											<xsl:for-each select="OR8">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0,2in; ">
											<xsl:for-each select="OR9">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style=" font-size:12px; background-color:#ECC5A8; text-align:center; width:0.40in; ">
											<span style="font:12px; font-family:Times New Roman; font-size:12px; font-weight:bold; vertical-align:middle; ">
												<xsl:value-of select="OR5+OR6+OR7+OR8+OR9"/>
											</span>
										</td>
										<td style="font-size:12px; text-align:center; width:0,2in; ">
											<xsl:for-each select="OR1">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0,2in; ">
											<xsl:for-each select="OR3">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style=" font-size:12px; background-color:#ECC5A8; text-align:center; width:0.40in; ">
											<span style="font:12px; font-family:Times New Roman; font-size:12px; font-weight:bold; vertical-align:middle; ">
												<xsl:value-of select="OR1+OR3"/>
											</span>
										</td>
										<td style="font-size:12px; text-align:center; width:0.2in; ">
											<xsl:for-each select="C1">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0.2in; ">
											<xsl:for-each select="C2">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0.2in; ">
											<xsl:for-each select="C3">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0.2in; ">
											<xsl:for-each select="C4">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style="font-size:12px; text-align:center; width:0.2in; ">
											<xsl:for-each select="C5">
												<span style="font:12px; font-family:ti; font-size:12px; vertical-align:middle; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</td>
										<td style=" font-size:12px; background-color:#ECC5A8; text-align:center; width:0.40in; ">
											<span style="font:12px; font-family:Times New Roman; font-size:12px; font-weight:bold; vertical-align:middle; ">
												<xsl:value-of select="C1+C2+C3+C4+C5"/>
											</span>
										</td>
										<td style=" font-size:12px; background-color:#ECC5A8;text-align:center; width:0.38in; ">
											<span style="font:12px; font-family:Times New Roman; font-size:12px; font-weight:bold; vertical-align:middle; ">
												<xsl:value-of select="OF0+OF1+OF2+OF3+OF4+OF5+OF6+OF7+OF8+OR5+OR6+OR7+OR8+OR9+OR1+OR3+C1+C2+C3+C4+C5"/>
											</span>
										</td>
									</tr>
									</xsl:if>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
					</tbody>
				</table>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
