<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2011 sp1 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:clitype="clitype" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:iso4217="http://www.xbrl.org/2003/iso4217" xmlns:ix="http://www.xbrl.org/2008/inlineXBRL" xmlns:java="java" xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:xbrldi="http://xbrl.org/2006/xbrldi" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:altova="http://www.altova.com" xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:svg="http://www.w3.org/2000/svg" exclude-result-prefixes="clitype fn iso4217 ix java link xbrldi xbrli xlink xs xsi altova">
	<xsl:output version="1.0" method="xml" encoding="UTF-8" indent="no"/>
	<xsl:param name="SV_OutputFormat" select="'PDF'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:variable name="fo:layout-master-set">
		<fo:layout-master-set>
			<fo:simple-page-master master-name="page-master-261868928-even" margin-left="0.5in" margin-right="0.5in" page-height="8.27in" page-width="11.69in" margin-top="0.10in" margin-bottom="0.10in">
				<fo:region-body margin-top="0.40in" margin-bottom="0.40in" column-count="1" column-gap="0.50in"/>
			</fo:simple-page-master>
			<fo:simple-page-master master-name="page-master-261868928-odd" margin-left="0.5in" margin-right="0.5in" page-height="8.27in" page-width="11.69in" margin-top="0.10in" margin-bottom="0.10in">
				<fo:region-body margin-top="0.40in" margin-bottom="0.40in" column-count="1" column-gap="0.50in"/>
			</fo:simple-page-master>
			<fo:page-sequence-master master-name="page-master-261868928">
				<fo:repeatable-page-master-alternatives>
					<fo:conditional-page-master-reference master-reference="page-master-261868928-even" odd-or-even="even"/>
					<fo:conditional-page-master-reference master-reference="page-master-261868928-odd" odd-or-even="odd"/>
				</fo:repeatable-page-master-alternatives>
			</fo:page-sequence-master>
		</fo:layout-master-set>
	</xsl:variable>
	<xsl:variable name="altova:nPxPerIn" select="96"/>
	<xsl:template match="/">
		<fo:root>
			<xsl:copy-of select="$fo:layout-master-set"/>
			<fo:page-sequence force-page-count="no-force" master-reference="page-master-261868928" initial-page-number="auto" format="1">
				<fo:flow flow-name="xsl-region-body">
					<fo:block>	
							<fo:block font-size="14px" font-weight="bold" font-family="Times New Roman" height="auto" text-align="left" width="auto" margin-right="100% - auto" margin="0pt">
													<xsl:for-each select="$XML">
														<xsl:for-each select="dataArray">
															<xsl:for-each select="dataArray">
																<xsl:if test="status='Confirmed' and position()=1">
																	<fo:block>
																	<fo:inline font="0.10in" font-family="Times New Roman" >
																	<xsl:text>Emerimet e Reja per Strukture/Konfirmuar</xsl:text>
																		</fo:inline>
																	</fo:block>							
																</xsl:if>
																<xsl:if test="status='All' and position()=1">
																	<fo:block>
																	<fo:inline font="0.10in" font-family="Times New Roman">
																	<xsl:text>Emerimet e Reja per Strukture</xsl:text>																	
																	</fo:inline>
																	</fo:block>								
																</xsl:if>
																<xsl:if test="position()=1">
																	<xsl:value-of select="date" />
																</xsl:if>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
							</fo:block>					
							
												
						<xsl:if test="$XML">
							<fo:table background-color="white" font="12" font-family="Times New Roman" height="auto" table-omit-footer-at-break="true" display-align="center" table-layout="fixed" width="auto" border="solid 1pt black" border-spacing="-1pt">
								<fo:table-column column-width="2in"/>
								<fo:table-column column-width="proportional-column-width(1)"/>
								<fo:table-column column-width="proportional-column-width(1)"/>
								<fo:table-column column-width="proportional-column-width(1)"/>
								<fo:table-column column-width="proportional-column-width(1)"/>
								<fo:table-column column-width="proportional-column-width(1)"/>
								<fo:table-column column-width="proportional-column-width(1)"/>
								<fo:table-column column-width="proportional-column-width(1)"/>
								<fo:table-column column-width="proportional-column-width(1)"/>
								<fo:table-column column-width="proportional-column-width(1)"/>
								<fo:table-column column-width="0.400in"/>
								<fo:table-column column-width="proportional-column-width(1)"/>
								<fo:table-column column-width="proportional-column-width(1)"/>
								<fo:table-column column-width="proportional-column-width(1)"/>
								<fo:table-column column-width="proportional-column-width(1)"/>
								<fo:table-column column-width="proportional-column-width(1)"/>
								<fo:table-column column-width="0.400in"/>
								<fo:table-column column-width="proportional-column-width(1)"/>
								<fo:table-column column-width="proportional-column-width(1)"/>
								<fo:table-column column-width="0.400in"/>
								<fo:table-column column-width="0.300in"/>
								<fo:table-column column-width="0.300in"/>
								<fo:table-column column-width="0.300in"/>
								<fo:table-column column-width="0.300in"/>
								<fo:table-column column-width="0.300in"/>
								<fo:table-column column-width="0.400in"/>
								<fo:table-column column-width="0.380in"/>
								<xsl:variable name="altova:CurrContextGrid_0FCA5CD0" select="."/>
											
								<fo:table-header background-color="#dce9f2" color="black" font="0.13in" font-family="Times New Roman" font-weight="bold" start-indent="0pt">
									
									<fo:table-row background-color="#dce9f2" height="12px" text-align="center">
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>EMERTIMI I STRUKTURES</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>OF0</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>OF1</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>OF2</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>OF3</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>OF4</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>OF5</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>OF6</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>OF7</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>OF8</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>Shuma</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>OR5</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>OR6</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>OR7</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>OR8</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>OR9</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>Shuma</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>OR1</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>OR3</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>Shuma</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>C1</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>C2</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>C3</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>C4</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>C5</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>Shuma</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small">
													<xsl:text>Totali </xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
									</fo:table-row>
								</fo:table-header>
							
								<fo:table-body display-align="center" start-indent="0pt">
									<xsl:variable name="altova:tablerows">
											
									<fo:table-row height="12px" background-color="#ECC5A8">
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font="0.10in" font-family="Times New Roman" font-size="x-small" font-weight="bold" table-omit-footer-at-break="true">
													<xsl:text>TOTAL FA</xsl:text>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
												
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="sum(//dataArray/OF0) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="sum(//dataArray/OF1) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="sum(//dataArray/OF2) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="sum(//dataArray/OF3) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="sum(//dataArray/OF4) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="sum(//dataArray/OF5) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="sum(//dataArray/OF6) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="sum(//dataArray/OF7) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="sum(//dataArray/OF8) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="(sum(//dataArray/OF0)+sum(//dataArray/OF1)+sum(//dataArray/OF2)+sum(//dataArray/OF3)+sum(//dataArray/OF4)+sum(//dataArray/OF5)+sum(//dataArray/OF6)+sum(//dataArray/OF7)+sum(//dataArray/OF8)) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="sum(//dataArray/OR5) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="sum(//dataArray/OR6) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="sum(//dataArray/OR7) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="sum(//dataArray/OR8) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="sum(//dataArray/OR9) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="(sum(//dataArray/OR5)+sum(//dataArray/OR6)+sum(//dataArray/OR7)+sum(//dataArray/OR8)+sum(//dataArray/OR9)) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="sum(//dataArray/OR1) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="sum(//dataArray/OR3) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="(sum(//dataArray/OR1)+sum(//dataArray/OR3)) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="sum(//dataArray/C1) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="sum(//dataArray/C2) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="sum(//dataArray/C3) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="sum(//dataArray/C4) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="sum(//dataArray/C5) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="(sum(//dataArray/C1)+sum(//dataArray/C2)+sum(//dataArray/C3)+sum(//dataArray/C4)+sum(//dataArray/C5)) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
										<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
											<fo:block text-align="center">
												<fo:inline font-family="Times New Roman" font-weight="bold" display-align="center">
													<xsl:value-of select="(sum(//dataArray/OF0)+ sum(//dataArray/OF1)+sum(//dataArray/OF2)+sum(//dataArray/OF3)+sum(//dataArray/OF4)+sum(//dataArray/OF5)+sum(//dataArray/OF6)+sum(//dataArray/OF7)+sum(//dataArray/OF8)+sum(//dataArray/OR5)+sum(//dataArray/OR6)+sum(//dataArray/OR7)+sum(//dataArray/OR8)+sum(//dataArray/OR9)+sum(//dataArray/OR1)+sum(//dataArray/OR3)+sum(//dataArray/C1)+sum(//dataArray/C2)+sum(//dataArray/C3)+sum(//dataArray/C4)+sum(//dataArray/C5)) div 2"/>
												</fo:inline>
											</fo:block>
										</fo:table-cell>
									</fo:table-row>

										<xsl:for-each select="$XML">
											<xsl:for-each select="dataArray">
												<xsl:for-each select="dataArray">												
												<xsl:if test="type='force'">
													<fo:table-row height="12px" background-color="#D3D1D2" font-weight="bold" text-align="center" display-align="center">
														<fo:table-cell font-size="x-small"  border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="unit">
																	<xsl:variable name="value-of-template_0BEF9988">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0BEF9988),'&#x200B;')">
																			<fo:block>
																				<xsl:copy-of select="$value-of-template_0BEF9988"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline>
																				<xsl:copy-of select="$value-of-template_0BEF9988"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OF0">
																	<xsl:variable name="value-of-template_0F930130">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F930130),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930130"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930130"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OF1">
																	<xsl:variable name="value-of-template_0F930130">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F930130),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930130"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930130"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font="12" font-family="Times New Roman" font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OF2">
																	<xsl:variable name="value-of-template_0F930050">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F930050),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930050"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930050"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OF3">
																	<xsl:variable name="value-of-template_0F92FF70">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F92FF70),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F92FF70"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F92FF70"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OF4">
																	<xsl:variable name="value-of-template_0F92FE90">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F92FE90),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F92FE90"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F92FE90"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OF5">
																	<xsl:variable name="value-of-template_0F92FDB0">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F92FDB0),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F92FDB0"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F92FDB0"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OF6">
																	<xsl:variable name="value-of-template_0F92FCD0">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F92FCD0),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F92FCD0"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F92FCD0"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OF7">
																	<xsl:variable name="value-of-template_0F92FBF0">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F92FBF0),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F92FBF0"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F92FBF0"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OF8">
																	<xsl:variable name="value-of-template_0F92FB10">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F92FB10),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F92FB10"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F92FB10"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell background-color="#ECC5A8" font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" font-weight="bold" display-align="center">
																	<xsl:value-of select="OF0+OF1+OF2+OF3+OF4+OF5+OF6+OF7+OF8"/>
																</fo:inline>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OR5">
																	<xsl:variable name="value-of-template_0F930670">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F930670),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930670"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930670"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OR6">
																	<xsl:variable name="value-of-template_0F930910">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F930910),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930910"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930910"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OR7">
																	<xsl:variable name="value-of-template_0F9309F0">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F9309F0),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F9309F0"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F9309F0"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OR8">
																	<xsl:variable name="value-of-template_0F9304B0">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F9304B0),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F9304B0"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F9304B0"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OR9">
																	<xsl:variable name="value-of-template_0F930750">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F930750),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930750"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930750"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell background-color="#ECC5A8" font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" font-weight="bold" display-align="center">
																	<xsl:value-of select="OR5+OR6+OR7+OR8+OR9"/>
																</fo:inline>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OR1">
																	<xsl:variable name="value-of-template_0F930830">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F930830),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930830"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930830"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OR3">
																	<xsl:variable name="value-of-template_0BEF9EC8">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0BEF9EC8),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0BEF9EC8"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0BEF9EC8"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell background-color="#ECC5A8" font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" font-weight="bold" display-align="center">
																	<xsl:value-of select="OR1+OR3"/>
																</fo:inline>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="C1">
																	<xsl:variable name="value-of-template_0BEF9DE8">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0BEF9DE8),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0BEF9DE8"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0BEF9DE8"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="C2">
																	<xsl:variable name="value-of-template_0BEF9D08">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0BEF9D08),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0BEF9D08"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0BEF9D08"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="C3">
																	<xsl:variable name="value-of-template_0BEF9C28">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0BEF9C28),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0BEF9C28"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0BEF9C28"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="C4">
																	<xsl:variable name="value-of-template_0BEF9B48">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0BEF9B48),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0BEF9B48"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0BEF9B48"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="C5">
																	<xsl:variable name="value-of-template_0BEF9A68">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0BEF9A68),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0BEF9A68"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0BEF9A68"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell background-color="#ECC5A8" font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" font-weight="bold" display-align="center">
																	<xsl:value-of select="C1+C2+C3+C4+C5"/>
																</fo:inline>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell background-color="#ECC5A8" font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" font-weight="bold" display-align="center">
																	<xsl:value-of select="OF0+OF1+OF2+OF3+OF4+OF5+OF6+OF7+OF8+OR5+OR6+OR7+OR8+OR9+OR1+OR3+C1+C2+C3+C4+C5"/>
																</fo:inline>
															</fo:block>
														</fo:table-cell>
													</fo:table-row>
													</xsl:if>
													<xsl:if test="type='unit'">
													<fo:table-row height="12px" display-align="center">
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="right">
																<xsl:for-each select="unit">
																	<xsl:variable name="value-of-template_0BEF9988">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0BEF9988),'&#x200B;')">
																			<fo:block>
																				<xsl:copy-of select="$value-of-template_0BEF9988"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline>
																				<xsl:copy-of select="$value-of-template_0BEF9988"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OF0">
																	<xsl:variable name="value-of-template_0F930130">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F930130),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930130"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930130"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OF1">
																	<xsl:variable name="value-of-template_0F930130">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F930130),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930130"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930130"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font="12" font-family="Times New Roman" font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OF2">
																	<xsl:variable name="value-of-template_0F930050">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F930050),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930050"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930050"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OF3">
																	<xsl:variable name="value-of-template_0F92FF70">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F92FF70),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F92FF70"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F92FF70"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OF4">
																	<xsl:variable name="value-of-template_0F92FE90">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F92FE90),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F92FE90"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F92FE90"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OF5">
																	<xsl:variable name="value-of-template_0F92FDB0">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F92FDB0),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F92FDB0"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F92FDB0"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OF6">
																	<xsl:variable name="value-of-template_0F92FCD0">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F92FCD0),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F92FCD0"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F92FCD0"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OF7">
																	<xsl:variable name="value-of-template_0F92FBF0">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F92FBF0),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F92FBF0"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F92FBF0"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OF8">
																	<xsl:variable name="value-of-template_0F92FB10">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F92FB10),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F92FB10"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F92FB10"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell background-color="#ECC5A8" font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" font-weight="bold" display-align="center">
																	<xsl:value-of select="OF0+OF1+OF2+OF3+OF4+OF5+OF6+OF7+OF8"/>
																</fo:inline>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OR5">
																	<xsl:variable name="value-of-template_0F930670">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F930670),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930670"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930670"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OR6">
																	<xsl:variable name="value-of-template_0F930910">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F930910),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930910"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930910"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OR7">
																	<xsl:variable name="value-of-template_0F9309F0">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F9309F0),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F9309F0"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F9309F0"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OR8">
																	<xsl:variable name="value-of-template_0F9304B0">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F9304B0),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F9304B0"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F9304B0"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OR9">
																	<xsl:variable name="value-of-template_0F930750">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F930750),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930750"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930750"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell background-color="#ECC5A8" font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" font-weight="bold" display-align="center">
																	<xsl:value-of select="OR5+OR6+OR7+OR8+OR9"/>
																</fo:inline>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OR1">
																	<xsl:variable name="value-of-template_0F930830">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0F930830),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930830"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0F930830"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="OR3">
																	<xsl:variable name="value-of-template_0BEF9EC8">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0BEF9EC8),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0BEF9EC8"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0BEF9EC8"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell background-color="#ECC5A8" font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" font-weight="bold" display-align="center">
																	<xsl:value-of select="OR1+OR3"/>
																</fo:inline>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="C1">
																	<xsl:variable name="value-of-template_0BEF9DE8">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0BEF9DE8),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0BEF9DE8"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0BEF9DE8"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="C2">
																	<xsl:variable name="value-of-template_0BEF9D08">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0BEF9D08),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0BEF9D08"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0BEF9D08"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="C3">
																	<xsl:variable name="value-of-template_0BEF9C28">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0BEF9C28),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0BEF9C28"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0BEF9C28"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="C4">
																	<xsl:variable name="value-of-template_0BEF9B48">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0BEF9B48),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0BEF9B48"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0BEF9B48"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<xsl:for-each select="C5">
																	<xsl:variable name="value-of-template_0BEF9A68">
																		<xsl:apply-templates/>
																	</xsl:variable>
																	<xsl:choose>
																		<xsl:when test="contains(string($value-of-template_0BEF9A68),'&#x200B;')">
																			<fo:block font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0BEF9A68"/>
																			</fo:block>
																		</xsl:when>
																		<xsl:otherwise>
																			<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" display-align="center">
																				<xsl:copy-of select="$value-of-template_0BEF9A68"/>
																			</fo:inline>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:for-each>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell background-color="#ECC5A8" font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" font-weight="bold" display-align="center">
																	<xsl:value-of select="C1+C2+C3+C4+C5"/>
																</fo:inline>
															</fo:block>
														</fo:table-cell>
														<fo:table-cell background-color="#ECC5A8" font-size="x-small" border="solid 1pt black" padding="0" display-align="center">
															<fo:block text-align="center">
																<fo:inline font="0.13in" font-family="Times New Roman" font-size="x-small" font-weight="bold" display-align="center">
																	<xsl:value-of select="OF0+ OF1+OF2+OF3+OF4+OF5+OF6+OF7+OF8+OR5+OR6+OR7+OR8+OR9+OR1+OR3+C1+C2+C3+C4+C5"/>
																</fo:inline>
															</fo:block>
														</fo:table-cell>
													</fo:table-row>
													</xsl:if>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:variable>
									<xsl:choose>
										<xsl:when test="string($altova:tablerows)">
											<xsl:copy-of select="$altova:tablerows"/>
										</xsl:when>
										<xsl:otherwise>
											<fo:table-row>
												<fo:table-cell>
													<fo:block/>
												</fo:table-cell>
											</fo:table-row>
										</xsl:otherwise>
									</xsl:choose>
								</fo:table-body>
							</fo:table>
						</xsl:if>
					</fo:block>
					<fo:block id="SV_RefID_PageTotal"/>
				</fo:flow>
			</fo:page-sequence>
		</fo:root>
	</xsl:template>
	<xsl:template name="double-backslash">
		<xsl:param name="text"/>
		<xsl:param name="text-length"/>
		<xsl:variable name="text-after-bs" select="substring-after($text, '\')"/>
		<xsl:variable name="text-after-bs-length" select="string-length($text-after-bs)"/>
		<xsl:choose>
			<xsl:when test="$text-after-bs-length = 0">
				<xsl:choose>
					<xsl:when test="substring($text, $text-length) = '\'">
						<xsl:value-of select="concat(substring($text,1,$text-length - 1), '\\')"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="$text"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="concat(substring($text,1,$text-length - $text-after-bs-length - 1), '\\')"/>
				<xsl:call-template name="double-backslash">
					<xsl:with-param name="text" select="$text-after-bs"/>
					<xsl:with-param name="text-length" select="$text-after-bs-length"/>
				</xsl:call-template>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	<xsl:template name="altova:MakeValueAbsoluteIfPixels">
		<xsl:param name="sValue"/>
		<xsl:variable name="sBeforePx" select="substring-before($sValue, 'px')"/>
		<xsl:choose>
			<xsl:when test="$sBeforePx">
				<xsl:variable name="nLengthOfInteger">
					<xsl:call-template name="altova:GetCharCountOfIntegerAtEndOfString">
						<xsl:with-param name="sText" select="$sBeforePx"/>
					</xsl:call-template>
				</xsl:variable>
				<xsl:variable name="nPosOfInteger" select="string-length($sBeforePx) - $nLengthOfInteger + 1"/>
				<xsl:variable name="nValuePx" select="substring($sBeforePx, $nPosOfInteger)"/>
				<xsl:variable name="nValueIn" select="number($nValuePx) div number($altova:nPxPerIn)"/>
				<xsl:variable name="nLengthBeforeInteger" select="string-length($sBeforePx) - $nLengthOfInteger"/>
				<xsl:variable name="sRest">
					<xsl:call-template name="altova:MakeValueAbsoluteIfPixels">
						<xsl:with-param name="sValue" select="substring-after($sValue, 'px')"/>
					</xsl:call-template>
				</xsl:variable>
				<xsl:value-of select="concat(substring($sBeforePx, 1, $nLengthBeforeInteger), string($nValueIn), 'in', $sRest)"/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="$sValue"/>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	<xsl:template name="altova:GetCharCountOfIntegerAtEndOfString">
		<xsl:param name="sText"/>
		<xsl:variable name="sLen" select="string-length($sText)"/>
		<xsl:variable name="cLast" select="substring($sText, $sLen)"/>
		<xsl:choose>
			<xsl:when test="number($cLast) &gt;= 0 and number($cLast) &lt;= 9">
				<xsl:variable name="nResultOfRest">
					<xsl:call-template name="altova:GetCharCountOfIntegerAtEndOfString">
						<xsl:with-param name="sText" select="substring($sText, 1, $sLen - 1)"/>
					</xsl:call-template>
				</xsl:variable>
				<xsl:value-of select="$nResultOfRest + 1"/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:text>0</xsl:text>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
</xsl:stylesheet>
